#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install

script:
  - ng build --prod
  - npm run precache

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    recipients:
      - simone.coletta@scquadro.it
    on_failure: change
    on_success: change